package com.spring.mybatis.model;

import lombok.Data;

@Data
public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.name
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.strategy
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    private String strategy;

}