package com.ymjia.demo.application.example;

import java.util.ArrayList;
import java.util.List;

public class ValidatePasswordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public ValidatePasswordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("trade_type is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("trade_type is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("trade_type =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("trade_type <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("trade_type >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("trade_type >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("trade_type <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("trade_type <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("trade_type like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("trade_type not like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<String> values) {
            addCriterion("trade_type in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<String> values) {
            addCriterion("trade_type not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("trade_type between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("trade_type not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andInstCodeIsNull() {
            addCriterion("inst_code is null");
            return (Criteria) this;
        }

        public Criteria andInstCodeIsNotNull() {
            addCriterion("inst_code is not null");
            return (Criteria) this;
        }

        public Criteria andInstCodeEqualTo(String value) {
            addCriterion("inst_code =", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeNotEqualTo(String value) {
            addCriterion("inst_code <>", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeGreaterThan(String value) {
            addCriterion("inst_code >", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inst_code >=", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeLessThan(String value) {
            addCriterion("inst_code <", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeLessThanOrEqualTo(String value) {
            addCriterion("inst_code <=", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeLike(String value) {
            addCriterion("inst_code like", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeNotLike(String value) {
            addCriterion("inst_code not like", value, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeIn(List<String> values) {
            addCriterion("inst_code in", values, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeNotIn(List<String> values) {
            addCriterion("inst_code not in", values, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeBetween(String value1, String value2) {
            addCriterion("inst_code between", value1, value2, "instCode");
            return (Criteria) this;
        }

        public Criteria andInstCodeNotBetween(String value1, String value2) {
            addCriterion("inst_code not between", value1, value2, "instCode");
            return (Criteria) this;
        }

        public Criteria andRequestSnIsNull() {
            addCriterion("request_sn is null");
            return (Criteria) this;
        }

        public Criteria andRequestSnIsNotNull() {
            addCriterion("request_sn is not null");
            return (Criteria) this;
        }

        public Criteria andRequestSnEqualTo(String value) {
            addCriterion("request_sn =", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnNotEqualTo(String value) {
            addCriterion("request_sn <>", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnGreaterThan(String value) {
            addCriterion("request_sn >", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnGreaterThanOrEqualTo(String value) {
            addCriterion("request_sn >=", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnLessThan(String value) {
            addCriterion("request_sn <", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnLessThanOrEqualTo(String value) {
            addCriterion("request_sn <=", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnLike(String value) {
            addCriterion("request_sn like", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnNotLike(String value) {
            addCriterion("request_sn not like", value, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnIn(List<String> values) {
            addCriterion("request_sn in", values, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnNotIn(List<String> values) {
            addCriterion("request_sn not in", values, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnBetween(String value1, String value2) {
            addCriterion("request_sn between", value1, value2, "requestSn");
            return (Criteria) this;
        }

        public Criteria andRequestSnNotBetween(String value1, String value2) {
            addCriterion("request_sn not between", value1, value2, "requestSn");
            return (Criteria) this;
        }

        public Criteria andTimeStampIsNull() {
            addCriterion("time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andTimeStampIsNotNull() {
            addCriterion("time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStampEqualTo(String value) {
            addCriterion("time_stamp =", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotEqualTo(String value) {
            addCriterion("time_stamp <>", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampGreaterThan(String value) {
            addCriterion("time_stamp >", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampGreaterThanOrEqualTo(String value) {
            addCriterion("time_stamp >=", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampLessThan(String value) {
            addCriterion("time_stamp <", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampLessThanOrEqualTo(String value) {
            addCriterion("time_stamp <=", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampLike(String value) {
            addCriterion("time_stamp like", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotLike(String value) {
            addCriterion("time_stamp not like", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampIn(List<String> values) {
            addCriterion("time_stamp in", values, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotIn(List<String> values) {
            addCriterion("time_stamp not in", values, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampBetween(String value1, String value2) {
            addCriterion("time_stamp between", value1, value2, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotBetween(String value1, String value2) {
            addCriterion("time_stamp not between", value1, value2, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andEncryptDataIsNull() {
            addCriterion("encrypt_data is null");
            return (Criteria) this;
        }

        public Criteria andEncryptDataIsNotNull() {
            addCriterion("encrypt_data is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptDataEqualTo(String value) {
            addCriterion("encrypt_data =", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataNotEqualTo(String value) {
            addCriterion("encrypt_data <>", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataGreaterThan(String value) {
            addCriterion("encrypt_data >", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt_data >=", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataLessThan(String value) {
            addCriterion("encrypt_data <", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataLessThanOrEqualTo(String value) {
            addCriterion("encrypt_data <=", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataLike(String value) {
            addCriterion("encrypt_data like", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataNotLike(String value) {
            addCriterion("encrypt_data not like", value, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataIn(List<String> values) {
            addCriterion("encrypt_data in", values, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataNotIn(List<String> values) {
            addCriterion("encrypt_data not in", values, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataBetween(String value1, String value2) {
            addCriterion("encrypt_data between", value1, value2, "encryptData");
            return (Criteria) this;
        }

        public Criteria andEncryptDataNotBetween(String value1, String value2) {
            addCriterion("encrypt_data not between", value1, value2, "encryptData");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("signature not between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdIsNull() {
            addCriterion("orig_order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdIsNotNull() {
            addCriterion("orig_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdEqualTo(String value) {
            addCriterion("orig_order_id =", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdNotEqualTo(String value) {
            addCriterion("orig_order_id <>", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdGreaterThan(String value) {
            addCriterion("orig_order_id >", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("orig_order_id >=", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdLessThan(String value) {
            addCriterion("orig_order_id <", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdLessThanOrEqualTo(String value) {
            addCriterion("orig_order_id <=", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdLike(String value) {
            addCriterion("orig_order_id like", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdNotLike(String value) {
            addCriterion("orig_order_id not like", value, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdIn(List<String> values) {
            addCriterion("orig_order_id in", values, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdNotIn(List<String> values) {
            addCriterion("orig_order_id not in", values, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdBetween(String value1, String value2) {
            addCriterion("orig_order_id between", value1, value2, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigOrderIdNotBetween(String value1, String value2) {
            addCriterion("orig_order_id not between", value1, value2, "origOrderId");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnIsNull() {
            addCriterion("orig_request_sn is null");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnIsNotNull() {
            addCriterion("orig_request_sn is not null");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnEqualTo(String value) {
            addCriterion("orig_request_sn =", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnNotEqualTo(String value) {
            addCriterion("orig_request_sn <>", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnGreaterThan(String value) {
            addCriterion("orig_request_sn >", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnGreaterThanOrEqualTo(String value) {
            addCriterion("orig_request_sn >=", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnLessThan(String value) {
            addCriterion("orig_request_sn <", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnLessThanOrEqualTo(String value) {
            addCriterion("orig_request_sn <=", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnLike(String value) {
            addCriterion("orig_request_sn like", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnNotLike(String value) {
            addCriterion("orig_request_sn not like", value, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnIn(List<String> values) {
            addCriterion("orig_request_sn in", values, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnNotIn(List<String> values) {
            addCriterion("orig_request_sn not in", values, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnBetween(String value1, String value2) {
            addCriterion("orig_request_sn between", value1, value2, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andOrigRequestSnNotBetween(String value1, String value2) {
            addCriterion("orig_request_sn not between", value1, value2, "origRequestSn");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("amt is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("amt is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(String value) {
            addCriterion("amt =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(String value) {
            addCriterion("amt <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(String value) {
            addCriterion("amt >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(String value) {
            addCriterion("amt >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(String value) {
            addCriterion("amt <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(String value) {
            addCriterion("amt <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLike(String value) {
            addCriterion("amt like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotLike(String value) {
            addCriterion("amt not like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<String> values) {
            addCriterion("amt in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<String> values) {
            addCriterion("amt not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(String value1, String value2) {
            addCriterion("amt between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(String value1, String value2) {
            addCriterion("amt not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andReqResvFldIsNull() {
            addCriterion("req_resv_fld is null");
            return (Criteria) this;
        }

        public Criteria andReqResvFldIsNotNull() {
            addCriterion("req_resv_fld is not null");
            return (Criteria) this;
        }

        public Criteria andReqResvFldEqualTo(String value) {
            addCriterion("req_resv_fld =", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldNotEqualTo(String value) {
            addCriterion("req_resv_fld <>", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldGreaterThan(String value) {
            addCriterion("req_resv_fld >", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldGreaterThanOrEqualTo(String value) {
            addCriterion("req_resv_fld >=", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldLessThan(String value) {
            addCriterion("req_resv_fld <", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldLessThanOrEqualTo(String value) {
            addCriterion("req_resv_fld <=", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldLike(String value) {
            addCriterion("req_resv_fld like", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldNotLike(String value) {
            addCriterion("req_resv_fld not like", value, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldIn(List<String> values) {
            addCriterion("req_resv_fld in", values, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldNotIn(List<String> values) {
            addCriterion("req_resv_fld not in", values, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldBetween(String value1, String value2) {
            addCriterion("req_resv_fld between", value1, value2, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andReqResvFldNotBetween(String value1, String value2) {
            addCriterion("req_resv_fld not between", value1, value2, "reqResvFld");
            return (Criteria) this;
        }

        public Criteria andSendResultIsNull() {
            addCriterion("send_result is null");
            return (Criteria) this;
        }

        public Criteria andSendResultIsNotNull() {
            addCriterion("send_result is not null");
            return (Criteria) this;
        }

        public Criteria andSendResultEqualTo(Short value) {
            addCriterion("send_result =", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultNotEqualTo(Short value) {
            addCriterion("send_result <>", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultGreaterThan(Short value) {
            addCriterion("send_result >", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultGreaterThanOrEqualTo(Short value) {
            addCriterion("send_result >=", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultLessThan(Short value) {
            addCriterion("send_result <", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultLessThanOrEqualTo(Short value) {
            addCriterion("send_result <=", value, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultIn(List<Short> values) {
            addCriterion("send_result in", values, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultNotIn(List<Short> values) {
            addCriterion("send_result not in", values, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultBetween(Short value1, Short value2) {
            addCriterion("send_result between", value1, value2, "sendResult");
            return (Criteria) this;
        }

        public Criteria andSendResultNotBetween(Short value1, Short value2) {
            addCriterion("send_result not between", value1, value2, "sendResult");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Long value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Long value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Long value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Long value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Long value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Long value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Long> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Long> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Long value1, Long value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Long value1, Long value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Long value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Long value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Long value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Long value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Long value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Long value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Long> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Long> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Long value1, Long value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Long value1, Long value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validate_password
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}