package com.ymjia.demo.application.mapper;

import com.ymjia.demo.application.example.ValidatePasswordExample;
import com.ymjia.demo.application.model.ValidatePassword;
import com.ymjia.demo.application.sqlprovider.ValidatePasswordSqlProvider;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ValidatePasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @SelectProvider(type=ValidatePasswordSqlProvider.class, method="countByExample")
    long countByExample(ValidatePasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ValidatePasswordSqlProvider.class, method="deleteByExample")
    int deleteByExample(ValidatePasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @Delete({
        "delete from validate_password",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @Insert({
        "insert into validate_password (id, version, ",
        "trade_type, inst_code, ",
        "request_sn, time_stamp, ",
        "encrypt_data, signature, ",
        "orig_order_id, orig_request_sn, ",
        "amt, req_resv_fld, ",
        "send_result, create_at, ",
        "update_at)",
        "values (#{id,jdbcType=BIGINT}, #{version,jdbcType=VARCHAR}, ",
        "#{tradeType,jdbcType=VARCHAR}, #{instCode,jdbcType=VARCHAR}, ",
        "#{requestSn,jdbcType=VARCHAR}, #{timeStamp,jdbcType=VARCHAR}, ",
        "#{encryptData,jdbcType=VARCHAR}, #{signature,jdbcType=VARCHAR}, ",
        "#{origOrderId,jdbcType=VARCHAR}, #{origRequestSn,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=VARCHAR}, #{reqResvFld,jdbcType=VARCHAR}, ",
        "#{sendResult,jdbcType=SMALLINT}, #{createAt,jdbcType=BIGINT}, ",
        "#{updateAt,jdbcType=BIGINT})"
    })
    int insert(ValidatePassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @InsertProvider(type=ValidatePasswordSqlProvider.class, method="insertSelective")
    int insertSelective(ValidatePassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @SelectProvider(type=ValidatePasswordSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="version", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="trade_type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="inst_code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="request_sn", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="time_stamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="encrypt_data", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="signature", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orig_order_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orig_request_sn", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="amt", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="req_resv_fld", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="send_result", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="create_at", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="update_at", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<ValidatePassword> selectByExample(ValidatePasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, version, trade_type, inst_code, request_sn, time_stamp, encrypt_data, signature, ",
        "orig_order_id, orig_request_sn, amt, req_resv_fld, send_result, create_at, update_at",
        "from validate_password",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="version", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="trade_type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="inst_code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="request_sn", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="time_stamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="encrypt_data", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="signature", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orig_order_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orig_request_sn", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="amt", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="req_resv_fld", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="send_result", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="create_at", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="update_at", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    ValidatePassword selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ValidatePasswordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ValidatePassword record, @Param("example") ValidatePasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ValidatePasswordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ValidatePassword record, @Param("example") ValidatePasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ValidatePasswordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ValidatePassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validate_password
     *
     * @mbg.generated
     */
    @Update({
        "update validate_password",
        "set version = #{version,jdbcType=VARCHAR},",
          "trade_type = #{tradeType,jdbcType=VARCHAR},",
          "inst_code = #{instCode,jdbcType=VARCHAR},",
          "request_sn = #{requestSn,jdbcType=VARCHAR},",
          "time_stamp = #{timeStamp,jdbcType=VARCHAR},",
          "encrypt_data = #{encryptData,jdbcType=VARCHAR},",
          "signature = #{signature,jdbcType=VARCHAR},",
          "orig_order_id = #{origOrderId,jdbcType=VARCHAR},",
          "orig_request_sn = #{origRequestSn,jdbcType=VARCHAR},",
          "amt = #{amt,jdbcType=VARCHAR},",
          "req_resv_fld = #{reqResvFld,jdbcType=VARCHAR},",
          "send_result = #{sendResult,jdbcType=SMALLINT},",
          "create_at = #{createAt,jdbcType=BIGINT},",
          "update_at = #{updateAt,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ValidatePassword record);

    @Select("select * from validate_password where orig_order_id = #{0} and send_result <> 2 limit 1")
    ValidatePassword getObjectByOrigOrderId(String origOrderId);

    @Select("select * from validate_password where orig_request_sn = #{0} and send_result <> 2 limit 1")
    ValidatePassword getObjectByOrigRequestSn(String origRequestSn);

    @Select("select * from validate_password where orig_request_sn = #{0} and orig_order_id = #{1} and send_result <> 2 limit 1")
    ValidatePassword getObjectByOrigRequestSnId(String origRequestSn, String origOrderId);

    @Select("select id from validate_password where request_sn = #{0} limit 1")
    Long getObjectByRequestSn(String requestSn);
}