package com.spring.mybatis.service;

import com.spring.mybatis.model.Resources;

import java.util.List;

/**
 * Created by jiayongming on 2017/4/21.
 */
public interface ResourcesService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    int insert(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    Resources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    List<Resources> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbggenerated Fri Apr 21 14:22:56 CST 2017
     */
    int updateByPrimaryKey(Resources record);

}
